# Generated by Django 3.1.1 on 2020-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('water_line_compatible', models.BooleanField(default=False)),
                ('coffee_machine_models', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('coffee_flavor', models.BooleanField()),
                ('pack_size', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
